<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="6"
           failures="4"
           errors="0"
           skipped="0"
           time="16.523">
    <properties></properties>

            <testcase
                name="testVerifyBookingId"
                time="2.185"
                classname="Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf">

            <failure type="java.lang.AssertionError" message="
expected: &quot;nehra2&quot;
 but was: &quot;nehra1&quot;">
                <![CDATA[java.lang.AssertionError: 
expected: "nehra2"
 but was: "nehra1"
                Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf.testVerifyBookingId(TCIntegrationFlowDoSelf.java:82)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:483)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)org.testng.internal.Invoker.invokeMethod(Invoker.java:714)org.testng.internal.Invoker.retryFailed(Invoker.java:1049)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)org.testng.TestRunner.privateRun(TestRunner.java:767)org.testng.TestRunner.run(TestRunner.java:617)org.testng.SuiteRunner.runTest(SuiteRunner.java:348)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)org.testng.SuiteRunner.run(SuiteRunner.java:254)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)org.testng.TestNG.runSuitesLocally(TestNG.java:1149)org.testng.TestNG.run(TestNG.java:1057)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </failure>
    </testcase>
            <testcase
                name="testVerifyBookingId"
                time="2.358"
                classname="Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf">

            <failure type="java.lang.AssertionError" message="
expected: &quot;nehra2&quot;
 but was: &quot;nehra1&quot;">
                <![CDATA[java.lang.AssertionError: 
expected: "nehra2"
 but was: "nehra1"
                Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf.testVerifyBookingId(TCIntegrationFlowDoSelf.java:82)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:483)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)org.testng.internal.Invoker.invokeMethod(Invoker.java:714)org.testng.internal.Invoker.retryFailed(Invoker.java:1049)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)org.testng.TestRunner.privateRun(TestRunner.java:767)org.testng.TestRunner.run(TestRunner.java:617)org.testng.SuiteRunner.runTest(SuiteRunner.java:348)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)org.testng.SuiteRunner.run(SuiteRunner.java:254)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)org.testng.TestNG.runSuitesLocally(TestNG.java:1149)org.testng.TestNG.run(TestNG.java:1057)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </failure>
    </testcase>
            <testcase
                name="testVerifyBookingId"
                time="2.190"
                classname="Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf">

            <failure type="java.lang.AssertionError" message="
expected: &quot;nehra2&quot;
 but was: &quot;nehra1&quot;">
                <![CDATA[java.lang.AssertionError: 
expected: "nehra2"
 but was: "nehra1"
                Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf.testVerifyBookingId(TCIntegrationFlowDoSelf.java:82)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:483)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)org.testng.internal.Invoker.invokeMethod(Invoker.java:714)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)org.testng.TestRunner.privateRun(TestRunner.java:767)org.testng.TestRunner.run(TestRunner.java:617)org.testng.SuiteRunner.runTest(SuiteRunner.java:348)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)org.testng.SuiteRunner.run(SuiteRunner.java:254)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)org.testng.TestNG.runSuitesLocally(TestNG.java:1149)org.testng.TestNG.run(TestNG.java:1057)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </failure>
    </testcase>
            <testcase
                name="testVerifyBookingId"
                time="2.010"
                classname="Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf">

            <failure type="java.lang.AssertionError" message="
expected: &quot;nehra2&quot;
 but was: &quot;nehra1&quot;">
                <![CDATA[java.lang.AssertionError: 
expected: "nehra2"
 but was: "nehra1"
                Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf.testVerifyBookingId(TCIntegrationFlowDoSelf.java:82)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:483)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)org.testng.internal.Invoker.invokeMethod(Invoker.java:714)org.testng.internal.Invoker.retryFailed(Invoker.java:1049)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)org.testng.TestRunner.privateRun(TestRunner.java:767)org.testng.TestRunner.run(TestRunner.java:617)org.testng.SuiteRunner.runTest(SuiteRunner.java:348)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)org.testng.SuiteRunner.run(SuiteRunner.java:254)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)org.testng.TestNG.runSuitesLocally(TestNG.java:1149)org.testng.TestNG.run(TestNG.java:1057)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </failure>
    </testcase>


            <testcase
                name="testCreateBooking"
                time="2.203"
                classname="Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf">
            </testcase>
            <testcase
                name="createToken"
                time="5.577"
                classname="Assured.restAssuredFramework.Tests.Integration.TCIntegrationFlowDoSelf">
            </testcase>
</testsuite>
